spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  profiles:
    active: prod
gemini:
  api-key: ${GEMINI_API_KEY}
app:
  frontend-url: ${FRONTEND_URL:http://localhost:3000}
